export interface InvestmentDashboardDto {
  property: { id: string; nickname: string; currency: string; purchasePriceCents: number | null; purchaseCompletionDate: string | null };
  range: { from: string; to: string; preset: string };
  accountingBasis: string;
  formulas: Record<string, string>;
  metrics: {
    totalAcquisitionCostCents: number | null;
    totalCashInvestedCents: number;
    totalContributedCents: number;
    currentValueCents: number | null;
    currentValuationSource: string | null;
    currentMortgageBalanceCents: number;
    currentEquityCents: number | null;
    grossRentalIncomeCents: number;
    otherIncomeCents: number;
    operatingExpensesCents: number;
    noiCents: number;
    mortgageInterestCents: number;
    mortgagePrincipalCents: number;
    netCashFlowCents: number;
    capitalAppreciationCents: number | null;
    totalReturnCents: number | null;
    capitalRecoveredCents: number;
    recoveredBps: number | null;
    annualisedReturnBps: number | null;
    currentMonthlyRentCents: number | null;
    occupancyBps: number;
    grossYieldBps: number | null;
    purchaseGrossYieldBps: number | null;
    netYieldBps: number | null;
    purchaseNetYieldBps: number | null;
    operatingExpenseRatioBps: number | null;
    cashOnCashBps: number | null;
    simpleRoiBps: number | null;
    equityMultipleBps: number | null;
    xirr: number | null;
    returnExcludingAppreciationCents: number;
    ltvBps: number | null;
    initialLtvBps: number | null;
    equityFromPrincipalCents: number;
    debtServiceCents: number;
    breakEvenOccupancyBps: number | null;
    refinanceHeadroomCents: number | null;
    dscrBps: number | null;
    interestCoverageBps: number | null;
    recentMonthlyFreeCashFlowCents: number;
    recovery: { remainingCents: number; months: number | null; date: string | null };
  };
  owners: Array<{
    id: string; name: string; email: string | null; isMainLandlord: boolean;
    periods: Array<{ percentageBps: number; effectiveFrom: string; effectiveTo: string | null }>;
    currentOwnershipBps: number | null; contributedCents: number; allocatedIncomeCents: number;
    allocatedExpensesCents: number; allocatedPrincipalCents: number; distributionsCents: number;
    entitlementCents: number; distributionVarianceCents: number; currentEquityCents: number | null;
    recoveredBps: number | null; cashOnCashBps: number | null; xirr: number | null;
  }>;
  monthly: Array<{ month: string; incomeCents: number; expensesCents: number; netCashFlowCents: number }>;
  forecastMonthly: Array<{ month: string; incomeCents: number; expensesCents: number; netCashFlowCents: number; status: "forecast" }>;
  recoveryScenarios: Array<{ scenario: string; monthlyCashFlowCents: number; remainingCents: number; months: number | null; date: string | null }>;
  valuations: Array<{ id: string; date: string; valueCents: number; source: string }>;
  equityHistory: Array<{ date: string; valueCents: number; mortgageBalanceCents: number; equityCents: number; source: string }>;
  returnBreakdown: Array<{ component: string; amountCents: number }>;
  loans: Array<{ id: string; name: string; originalBalanceCents: number; currentBalanceCents: number; interestRateBps: number | null; repaymentType: string; monthlyPaymentCents: number | null }>;
  forecast: Record<string, unknown> | null;
  transactions: Array<{ id: string; date: string; type: string; category: string; description: string | null; amountCents: number; owner: string | null; status: string; source: string; sourceHref: string | null; notes: string | null }>;
  expenseBreakdown: Array<{ category: string; amountCents: number }>;
  issues: Array<{ severity: "warning" | "error"; code: string; message: string }>;
  disclaimer: string;
}
